import { writeFileSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import { parse } from 'yaml';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const yamlText = readFileSync(resolve(root, 'open-api/v0.yaml'), 'utf8');
const spec = parse(yamlText);

const ast = await openapiTS(spec);
const content = `// AUTO-GENERATED by \`pnpm gen:types\` — do not edit\n${astToString(ast)}`;

writeFileSync(resolve(root, 'src/api/types.ts'), content);
console.log('types written to src/api/types.ts');
